### ISSUE TITLE
Resizing file on fuse file system hangs

### ISSUE THREAD

**Issue by Lanchon** [quodlibet/mutagen#262] opened 2016-07-06 21:15 UTC
hi,
thanks for mutagen!

adding a tag with EasyMP3 used to work fine but now takes forever with recent linux kernels.

in particular, [this line] (https://github.com/quodlibet/mutagen/blob/master/mutagen/_util.py#L680) causes python to call C lib's [memmove on the mmap] (https://github.com/python/cpython/blob/master/Modules/mmapmodule.c#L684), and this in turn causes the kernel enter [noninterruptible sleep] (http://stackoverflow.com/questions/223644/what-is-an-uninterruptable-process) for a long time, eg **15 minutes to tag 60 MB mp3 file!!!**

this is not a bug in mutagen, but it renders the library useless. a simple workaround would be to copy the file contents to a temporary file instead of moving them in-place.

this would make mutagen safer too, given that if the tagging process is interrupted, mutagen as it is now corrupts the original mp3 file.

you can find more info on this issue [here] (https://github.com/Miserlou/SoundScrape/issues/101).

thank you.

**Comment by lazka** [comment] 2016-07-06 21:22
Which filesystem is the mp3 on?

**Comment by Lanchon** [comment] 2016-07-06 22:41
oh crap, you are right!!

i had forgotten all about it, i have a symlink from my ext4 ssd pointing into a rotating harddrive for music. and on top of that, the hd partition is fuse-mounted because it's ntfs!

```
/dev/sdb4 on /mnt/share type fuseblk (rw,nosuid,nodev,noatime,allow_other,default_permissions,blksize=4096)
```

ok so the interaction between memmove, mmap, fuse and ntfs-3g blows up. but how can it be that this used to work fine before? could i be wrong? maybe soundscrape used to not tag files? maybe i was using a different folder?

but anyway, do you think this is a 'wont fix'? what do you think about the possibility of file corruption when tagging?

**Comment by Lanchon** [comment] 2016-07-06 22:43
FYI, i just ran the same test on an ext4 partition (SSD), and sure enough the heretofore 15+ minute tagging operation became sub-second.

**Comment by lazka** [comment] 2016-07-06 22:48
This looks related:
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1572025

**Comment by Lanchon** [comment] 2016-07-06 22:51
absolutely! and it says

> Reverting to 3.13 or 3.19 works around the issue on 14.04.

and i was using a 3.19 kernel before :)

**Comment by lazka** [comment] 2016-07-07 06:49
Thanks for looking into this and confirming. I've had some other reproduce over IRC as well, but couldn't reproduce (maybe the filesize matters).

I would consider getting rid of mmap in mutagen, but on the other hand once everyone gets a new version through their distro they also get a fixed kernel...

Regarding file corruption with tagging: I plan to add API for this in mutagen at some point to make it easier (also see #241). Atm mutagen users can do it them self, by doing a copy, tag, fsync, rename. The only downside is in case of a file resize the file will be written twice.

**Comment by lazka** [comment] 2016-07-07 06:54
Ah, I have 4.6, where this supposedly is fixed.

**Comment by Lanchon** [comment] 2016-07-08 06:50
if you ask me, at least for those cases in which to tag a file the payload of the file has to be moved, for those cases at a minimum the payload move should always be atomic.

**Comment by lazka** [comment] 2016-07-17 17:50
Closing this.

I did some tests in #264 for a mmap alternative which should be less complex to handle for file systems and thus maybe less likely to hit bugs in the future.

**Closed by lazka** 2016-07-17 17:50 UTC
